// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type ChatData struct {
	ConversationID string `json:"conversationId"`
	Message        string `json:"message"`
}

type ChatMessage struct {
	Role    string `json:"role"` // system|user|assistant
	Content string `json:"content"`
}

type ChatRequest struct {
	RoleID    string                 `json:"roleId"`
	Model     string                 `json:"model,optional"`
	Messages  []ChatMessage          `json:"messages,optional"`
	TTSConfig map[string]interface{} `json:"ttsConfig,optional"`
}

type ChatResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    ChatData `json:"data"`
}

type HealthResponse struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type ProviderInfo struct {
	Name         string            `json:"name"`
	Type         string            `json:"type"`   // llm|asr|tts|moderation
	Status       string            `json:"status"` // online|offline|error
	Capabilities []string          `json:"capabilities,optional"`
	Config       map[string]string `json:"config,optional"`
}

type Role struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Avatar      string            `json:"avatar"`
	Description string            `json:"description"`
	Skills      []string          `json:"skills"`
	TTSDefault  map[string]string `json:"ttsDefault"`
}

type RolesResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    []Role `json:"data"`
}

type ServiceListResponse struct {
	Code    int            `json:"code"`
	Message string         `json:"message"`
	Data    []ProviderInfo `json:"data"`
}

type ServiceStatusResponse struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Data    ProviderInfo `json:"data"`
}

type WSFrame struct {
	Type    string      `json:"type"`
	Seq     int         `json:"seq,optional"`
	Content interface{} `json:"content,optional"`
}
