// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	chat "github.com/unclewu3242592726/CosTalk/backend/internal/handler/chat"
	health "github.com/unclewu3242592726/CosTalk/backend/internal/handler/health"
	role "github.com/unclewu3242592726/CosTalk/backend/internal/handler/role"
	service "github.com/unclewu3242592726/CosTalk/backend/internal/handler/service"
	"github.com/unclewu3242592726/CosTalk/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/chat/stream",
				Handler: chat.ChatStreamHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/health",
				Handler: health.HealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/roles",
				Handler: role.GetRolesHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/services",
				Handler: service.GetServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/services/:type",
				Handler: service.GetServicesByTypeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/services/:type/:name",
				Handler: service.GetServiceStatusHandler(serverCtx),
			},
		},
	)
}
